# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# first_user = User.create(name: 'Tom Herbal', photo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROWm_741qaM08Rn2xI5WTsmgSnwbgkoDdhrg&usqp=CAU', bio: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate possimus impedit ut, veritatis, unde reiciendis laboriosam maxime consequuntur commodi ratione, dolorum exercitationem quos? Aspernatur eum assumenda ullam laudantium porro ratione consequuntur quidem, excepturi hic atque libero sunt dolores perspiciatis laborum odio perferendis sit possimus! Omnis recusandae vitae error nostrum ipsum? Cumque id aliquid, laboriosam error maiores totam reprehenderit provident pariatur sint excepturi eos nulla eum expedita nesciunt aperiam accusantium blanditiis.', post_counter: 0)
# second_user = User.create(name: 'Lilly Bucha', photo: 'https://images.contentstack.io/v3/assets/blt36c2e63521272fdc/blt2e5f7f145e6f737c/5e9d17c4cb84e463e2ebd703/370x370_Chris-Dale.jpg', bio: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate possimus impedit ut, veritatis, unde reiciendis laboriosam maxime consequuntur commodi ratione, dolorum exercitationem quos? Aspernatur eum assumenda ullam laudantium porro ratione consequuntur quidem, excepturi hic atque libero sunt dolores perspiciatis laborum odio perferendis sit possimus! Omnis recusandae vitae error nostrum ipsum? Cumque id aliquid, laboriosam error maiores totam reprehenderit provident pariatur sint excepturi eos nulla eum expedita nesciunt aperiam accusantium blanditiis.', post_counter: 0)

# third_user = User.create(name: 'Tony Buchan', photo: 'https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Photo.png', bio: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate possimus impedit ut, veritatis, unde reiciendis laboriosam maxime consequuntur commodi ratione, dolorum exercitationem quos? Aspernatur eum assumenda ullam laudantium porro ratione consequuntur quidem, excepturi hic atque libero sunt dolores perspiciatis laborum odio perferendis sit possimus! Omnis recusandae vitae error nostrum ipsum? Cumque id aliquid, laboriosam error maiores totam reprehenderit provident pariatur sint excepturi eos nulla eum expedita nesciunt aperiam accusantium blanditiis.', post_counter: 0)

# fourth_user = User.create(name: 'Steve Banson', photo: 'https://png.pngtree.com/png-vector/20190710/ourmid/pngtree-user-vector-avatar-png-image_1541962.jpg', bio: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cupiditate possimus impedit ut, veritatis, unde reiciendis laboriosam maxime consequuntur commodi ratione, dolorum exercitationem quos? Aspernatur eum assumenda ullam laudantium porro ratione consequuntur quidem, excepturi hic atque libero sunt dolores perspiciatis laborum odio perferendis sit possimus! Omnis recusandae vitae error nostrum ipsum? Cumque id aliquid, laboriosam error maiores totam reprehenderit provident pariatur sint excepturi eos nulla eum expedita nesciunt aperiam accusantium blanditiis.', post_counter: 0)
